/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_engineaccount_free: (a: number, b: number) => void;
export const __wbg_enginesession_free: (a: number, b: number) => void;
export const __wbg_inboundresult_free: (a: number, b: number) => void;
export const engine_version: () => [number, number];
export const engineaccount_createInboundSession: (a: number, b: number, c: number, d: number, e: number) => [number, number, number];
export const engineaccount_createOutboundSession: (a: number, b: number, c: number, d: number, e: number) => [number, number, number];
export const engineaccount_curve25519Key: (a: number) => [number, number];
export const engineaccount_ed25519Key: (a: number) => [number, number];
export const engineaccount_fallbackKey: (a: number) => [number, number, number];
export const engineaccount_fromPickle: (a: number, b: number, c: number, d: number) => [number, number, number];
export const engineaccount_generateFallbackKey: (a: number) => void;
export const engineaccount_generateOneTimeKeys: (a: number, b: number) => [number, number, number];
export const engineaccount_markKeysAsPublished: (a: number) => void;
export const engineaccount_maxOneTimeKeys: (a: number) => number;
export const engineaccount_new: () => number;
export const engineaccount_oneTimeKeys: (a: number) => [number, number, number];
export const engineaccount_pickle: (a: number, b: number, c: number) => [number, number, number, number];
export const engineaccount_sign: (a: number, b: number, c: number) => [number, number];
export const enginesession_decrypt: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const enginesession_encrypt: (a: number, b: number, c: number) => [number, number, number];
export const enginesession_fromPickle: (a: number, b: number, c: number, d: number) => [number, number, number];
export const enginesession_hasReceivedMessage: (a: number) => number;
export const enginesession_pickle: (a: number, b: number, c: number) => [number, number, number, number];
export const enginesession_sessionId: (a: number) => [number, number];
export const inboundresult_plaintext: (a: number) => [number, number];
export const inboundresult_takeSession: (a: number) => [number, number, number];
export const prekey_message_session_id: (a: number, b: number) => [number, number, number, number];
export const safety_number: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number) => [number, number, number, number];
export const verify_ed25519: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number];
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
