import pkg from '../package.json' with { type: 'json' };

export const APP_NAME = 'Voxium';
export const APP_VERSION = pkg.version;

export const API_VERSION = 'v1';

export const LIMITS = {
  USERNAME_MIN: 3,
  USERNAME_MAX: 32,
  DISPLAY_NAME_MAX: 64,
  PASSWORD_MIN: 8,
  PASSWORD_MAX: 128,
  SERVER_NAME_MIN: 2,
  SERVER_NAME_MAX: 100,
  CHANNEL_NAME_MIN: 1,
  CHANNEL_NAME_MAX: 100,
  MESSAGE_MAX: 4000,
  BIO_MAX: 500,
  MESSAGES_PER_PAGE: 50,
  MEMBERS_PER_PAGE: 100,
  MAX_SERVERS_PER_USER: 5,
  MAX_CHANNELS_PER_SERVER: 20,
  MAX_VOICE_USERS_PER_CHANNEL: 12,
  MAX_REACTIONS_PER_MESSAGE: 20,
  MAX_EMOJI_LENGTH: 32,
  CATEGORY_NAME_MIN: 1,
  CATEGORY_NAME_MAX: 100,
  MAX_CATEGORIES_PER_SERVER: 12,
  SEARCH_QUERY_MIN: 2,
  SEARCH_QUERY_MAX: 200,
  SEARCH_RESULTS_PER_PAGE: 25,
  ANNOUNCEMENT_TITLE_MIN: 3,
  ANNOUNCEMENT_TITLE_MAX: 200,
  ANNOUNCEMENT_CONTENT_MAX: 2000,
  REPORT_REASON_MIN: 10,
  REPORT_REASON_MAX: 1000,
  SUPPORT_MESSAGE_MIN: 1,
  SUPPORT_MESSAGE_MAX: 2000,
  TOTP_CODE_LENGTH: 6,
  TOTP_BACKUP_CODE_COUNT: 8,
} as const;

export const INVITE_CODE_LENGTH = 8;

export const WS_EVENTS = {
  MESSAGE_NEW: 'message:new',
  MESSAGE_UPDATE: 'message:update',
  MESSAGE_DELETE: 'message:delete',
  CHANNEL_CREATED: 'channel:created',
  CHANNEL_UPDATED: 'channel:updated',
  CHANNEL_DELETED: 'channel:deleted',
  CATEGORY_CREATED: 'category:created',
  CATEGORY_UPDATED: 'category:updated',
  CATEGORY_DELETED: 'category:deleted',
  MEMBER_JOINED: 'member:joined',
  MEMBER_LEFT: 'member:left',
  PRESENCE_UPDATE: 'presence:update',
  VOICE_CHANNEL_USERS: 'voice:channel_users',
  VOICE_USER_JOINED: 'voice:user_joined',
  VOICE_USER_LEFT: 'voice:user_left',
  VOICE_STATE_UPDATE: 'voice:state_update',
  VOICE_SPEAKING: 'voice:speaking',
  VOICE_SIGNAL: 'voice:signal',
  VOICE_ERROR: 'voice:error',
  VOICE_TRANSPORT_CREATED: 'voice:transport_created',
  VOICE_TRANSPORT_CONNECT: 'voice:transport:connect',
  VOICE_PRODUCE: 'voice:produce',
  VOICE_NEW_CONSUMER: 'voice:new_consumer',
  VOICE_CONSUMER_RESUME: 'voice:consumer:resume',
  VOICE_PRODUCER_CLOSED: 'voice:producer_closed',
  VOICE_RTP_CAPABILITIES: 'voice:rtp_capabilities',
  TYPING_START: 'typing:start',
  TYPING_STOP: 'typing:stop',
  CHANNEL_JOIN: 'channel:join',
  CHANNEL_LEAVE: 'channel:leave',
  VOICE_JOIN: 'voice:join',
  VOICE_LEAVE: 'voice:leave',
  VOICE_MUTE: 'voice:mute',
  VOICE_DEAF: 'voice:deaf',
  MESSAGE_REACTION_UPDATE: 'message:reaction_update',
  SERVER_UPDATED: 'server:updated',
  USER_UPDATED: 'user:updated',
  UNREAD_INIT: 'unread:init',
  DM_MESSAGE_NEW: 'dm:message:new',
  DM_MESSAGE_UPDATE: 'dm:message:update',
  DM_MESSAGE_DELETE: 'dm:message:delete',
  DM_TYPING_START: 'dm:typing:start',
  DM_TYPING_STOP: 'dm:typing:stop',
  DM_JOIN: 'dm:join',
  DM_MESSAGE_REACTION_UPDATE: 'dm:message:reaction_update',
  DM_UNREAD_INIT: 'dm:unread:init',
  DM_VOICE_OFFER: 'dm:voice:offer',
  DM_VOICE_JOINED: 'dm:voice:joined',
  DM_VOICE_LEFT: 'dm:voice:left',
  DM_VOICE_STATE_UPDATE: 'dm:voice:state_update',
  DM_VOICE_SPEAKING: 'dm:voice:speaking',
  DM_VOICE_SIGNAL: 'dm:voice:signal',
  DM_VOICE_JOIN: 'dm:voice:join',
  DM_VOICE_LEAVE: 'dm:voice:leave',
  DM_VOICE_MUTE: 'dm:voice:mute',
  DM_VOICE_DEAF: 'dm:voice:deaf',
  DM_VOICE_ENDED: 'dm:voice:ended',
  DM_VOICE_DECLINE: 'dm:voice:decline',
  FRIEND_REQUEST_RECEIVED: 'friend:request_received',
  FRIEND_REQUEST_ACCEPTED: 'friend:request_accepted',
  FRIEND_REMOVED: 'friend:removed',
  DM_CONVERSATION_DELETED: 'dm:conversation:deleted',
  MEMBER_ROLE_UPDATED: 'member:role_updated',
  MEMBER_KICKED: 'member:kicked',
  SERVER_DELETED: 'server:deleted',
  VOICE_SCREEN_SHARE_START: 'voice:screen_share:start',
  VOICE_SCREEN_SHARE_STOP: 'voice:screen_share:stop',
  VOICE_SCREEN_SHARE_STATE: 'voice:screen_share:state',
  ADMIN_METRICS: 'admin:metrics',
  ADMIN_SUBSCRIBE_METRICS: 'admin:subscribe_metrics',
  ADMIN_UNSUBSCRIBE_METRICS: 'admin:unsubscribe_metrics',
  ANNOUNCEMENT_NEW: 'announcement:new',
  ANNOUNCEMENT_INIT: 'announcement:init',
  REPORT_NEW: 'report:new',
  ADMIN_SUBSCRIBE_REPORTS: 'admin:subscribe_reports',
  ADMIN_UNSUBSCRIBE_REPORTS: 'admin:unsubscribe_reports',
  SUPPORT_MESSAGE_NEW: 'support:message:new',
  SUPPORT_STATUS_CHANGE: 'support:status_change',
  SUPPORT_TICKET_NEW: 'support:ticket:new',
  ADMIN_SUBSCRIBE_SUPPORT: 'admin:subscribe_support',
  ADMIN_UNSUBSCRIBE_SUPPORT: 'admin:unsubscribe_support',
  FORCE_LOGOUT: 'force:logout',
} as const;
