export const APP_NAME = 'Voxium';
export const APP_VERSION = '0.9.4';

export const API_VERSION = 'v1';

export const LIMITS = {
  USERNAME_MIN: 3,
  USERNAME_MAX: 32,
  DISPLAY_NAME_MAX: 64,
  PASSWORD_MIN: 8,
  PASSWORD_MAX: 128,
  SERVER_NAME_MIN: 2,
  SERVER_NAME_MAX: 100,
  CHANNEL_NAME_MIN: 1,
  CHANNEL_NAME_MAX: 100,
  MESSAGE_MAX: 4000,
  BIO_MAX: 500,
  MESSAGES_PER_PAGE: 50,
  MEMBERS_PER_PAGE: 100,
  MAX_SERVERS_PER_USER: 100,
  MAX_CHANNELS_PER_SERVER: 500,
  MAX_VOICE_USERS_PER_CHANNEL: 99,
  MAX_REACTIONS_PER_MESSAGE: 20,
  MAX_EMOJI_LENGTH: 32,
  CATEGORY_NAME_MIN: 1,
  CATEGORY_NAME_MAX: 100,
  MAX_CATEGORIES_PER_SERVER: 50,
} as const;

export const INVITE_CODE_LENGTH = 8;

export const WS_EVENTS = {
  MESSAGE_NEW: 'message:new',
  MESSAGE_UPDATE: 'message:update',
  MESSAGE_DELETE: 'message:delete',
  CHANNEL_CREATED: 'channel:created',
  CHANNEL_UPDATED: 'channel:updated',
  CHANNEL_DELETED: 'channel:deleted',
  CATEGORY_CREATED: 'category:created',
  CATEGORY_UPDATED: 'category:updated',
  CATEGORY_DELETED: 'category:deleted',
  MEMBER_JOINED: 'member:joined',
  MEMBER_LEFT: 'member:left',
  PRESENCE_UPDATE: 'presence:update',
  VOICE_USER_JOINED: 'voice:user_joined',
  VOICE_USER_LEFT: 'voice:user_left',
  VOICE_STATE_UPDATE: 'voice:state_update',
  VOICE_SPEAKING: 'voice:speaking',
  VOICE_SIGNAL: 'voice:signal',
  TYPING_START: 'typing:start',
  TYPING_STOP: 'typing:stop',
  CHANNEL_JOIN: 'channel:join',
  CHANNEL_LEAVE: 'channel:leave',
  VOICE_JOIN: 'voice:join',
  VOICE_LEAVE: 'voice:leave',
  VOICE_MUTE: 'voice:mute',
  VOICE_DEAF: 'voice:deaf',
  MESSAGE_REACTION_UPDATE: 'message:reaction_update',
  SERVER_UPDATED: 'server:updated',
  USER_UPDATED: 'user:updated',
  UNREAD_INIT: 'unread:init',
  DM_MESSAGE_NEW: 'dm:message:new',
  DM_MESSAGE_UPDATE: 'dm:message:update',
  DM_MESSAGE_DELETE: 'dm:message:delete',
  DM_TYPING_START: 'dm:typing:start',
  DM_TYPING_STOP: 'dm:typing:stop',
  DM_JOIN: 'dm:join',
  DM_MESSAGE_REACTION_UPDATE: 'dm:message:reaction_update',
  DM_UNREAD_INIT: 'dm:unread:init',
  DM_VOICE_OFFER: 'dm:voice:offer',
  DM_VOICE_JOINED: 'dm:voice:joined',
  DM_VOICE_LEFT: 'dm:voice:left',
  DM_VOICE_STATE_UPDATE: 'dm:voice:state_update',
  DM_VOICE_SPEAKING: 'dm:voice:speaking',
  DM_VOICE_SIGNAL: 'dm:voice:signal',
  DM_VOICE_JOIN: 'dm:voice:join',
  DM_VOICE_LEAVE: 'dm:voice:leave',
  DM_VOICE_MUTE: 'dm:voice:mute',
  DM_VOICE_DEAF: 'dm:voice:deaf',
  DM_VOICE_ENDED: 'dm:voice:ended',
  FRIEND_REQUEST_RECEIVED: 'friend:request_received',
  FRIEND_REQUEST_ACCEPTED: 'friend:request_accepted',
  FRIEND_REMOVED: 'friend:removed',
  DM_CONVERSATION_DELETED: 'dm:conversation:deleted',
  MEMBER_ROLE_UPDATED: 'member:role_updated',
  MEMBER_KICKED: 'member:kicked',
} as const;
